workingpath: /wherever/you/want/to/deploy
email: you@somenergia.coop
erpport: 18069
dbname: somenergia_ci
dbuser: myuser
dbpass: False
dbhost: False
empoweringCompany: '9993331111'

#skipDeploy: True # Just run the tests
#skipPipUpgrade: True # Do not upgrade Python packages
#upgradePipPackages: True # Upgrade any pip package with a new compatible version available
#keepDatabase: True # Do not reload the db if it exists
#reuseBackup: True # Uses the oldest local tarball to update de db
#forceDownload: True # Even if the local db backup exists download it
#runUnchanged: True # Run tests even if no changes detected
