#!/bin/bash
pidfile="$1"
if [ -e $pidfile ]; then
    pid=$(cat $pidfile)
    if kill -0 $pid 2>&1 > /dev/null ; then
        echo "Already running"
        exit 1
    else
        rm $pidfile
    fi
fi
echo $$ > $pidfile
 
"${@:2}"
result=$?

rm $pidfile

exit $result

