ubuntuDependencies:
- libxslt1-dev
- python-dev
- libxml2-dev
- zlib1g-dev
- postgresql-server-dev-all
- libjpeg-dev
#- redis-server
- postgresql
- libffi-dev
- mongodb-server
- virtualenvwrapper
- build-essential
- gcc
- g++
- python-pip
- pv
- libxmlsec1-dev # required by FACe_lib
- fontconfig
- libfontconfig1
- xfonts-75dpi

predeploy: # TODO: Not used yet, see installCustomPdfGenerator
- mkvirtualenv -p $(which python2) --system-site-packages erp
- wget http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
- wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
- sudo dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
# egenix-mx-base
- wget https://files.pythonhosted.org/packages/66/e6/e0709aedeb4a5c92a1aeb8c47ab50e9506eafc865806801bd3f01d72b671/egenix-mx-base-3.2.9.zip
- unzip egenix-mx-base-3.2.9.zip
- cd egenix-mx-base-3.2.9
- ./setup.py install

pipDependencies:
# client
- pytz
#- egenix-mx-base==3.2.9 # TODO: see predeploy steps for egenix
#- ruamel.venvgtk
- pyOpenSSL
# server
- pyreemote
- vatnumber
- mako
- pydot
- psycopg2<2.8
- blinker
- arrow
- Babel
- pymongo<3.0
- rq<1.0
- raven
- sentry
- psutil
- times
- xlwt
- FACe_lib
- pysftp
- redis
- osconf
- slugify
- fuzzywuzzy
- lockfile
- marshmallow>=2.0.0
- Python-Chart
- reportlab>=3.0
- osconf
- libcomxml<2.2.4
- unidecode
- pprintpp
- autoworker
- certifi
- python-sql
- rednose
- retrofix # l10n_ES_cobros_ventanilla
- pandas # by custom_search
- python-magic # by facturae
- tqdm # by giscedata_sup_territorials_2013_tec271_comer
- pyreemote # de la wiki
- oopgrade # de la wiki
- pypdftk # de la wiki
- dm.xmlsec.binding


pretasks:
- updateDatabase:
  # Download
  - scp somdevel@sf5.somenergia.coop:/var/backup/somenergia.sql.gz somenergia-$(date -I -d yesterday).sql.gz
  # Backup old database
  - echo ALTER DATABASE somenergia RENAME TO somenergia_$(ls somenergia-*.sql.gz | tail -n1 | sed 's/somenergia-\(....-..-..\).sql.gz/\1/' |  sed s/-//g; )  | psql
  # Load new database
  - createdb somenergia
  - zcat somenergia-$(date -I -d yesterday).sql.gz | psql -e somenergia
  # TODO: Adapting database to testing (emails...)
  # Update database
  - erpserver --update all --stop-after-init
  - psql -d somenergia -c "UPDATE res_partner_address SET email = 'oriol.piera@somenergia.coop'"

repositories:
# TODO: requires permisions from gisce
- path: libfacturacioatr
  url: git@github.com:gisce/libFacturacioATR.git
  #  url: https://github.com/gisce/libFacturacioATR.git
- path: erp
  user: Som-Energia
  branch: som_rolling
- path: orakwlum_client
  url: git@github.com:gisce/orakWlum-client.git
- path: CNMC-Client
  url: git@github.com:gisce/cnmc_client.git
- path: aeroo
  branch: openerp5
- path: aeroolib
  branch: openerp5
- path: mongodb_backend
- path: oorq
  branch: api_v5
- path: ooquery
- path: openerp-sentry
  branch: v5_legacy
- path: poweremail2
  url: git@github.com:gisce/poweremail.git
  branch: v5_backport
- path: poweremail_oorq
- path: spawn_oop
- path: ws_transactions
- path: sepa
- path: switching
- path: libComXML
- path: cchloader
  branch: gisce
- path: sippers
- path: ir_attachment_mongodb
- path: qreu
- path: enerdata
- path: ooop
  branch: xmlrpc_transaction
- path: arquia
- path: sii
- path: empowering
- path: gestionatr
- path: erp-empowering
  user: Som-Energia
- path: amoniak
  user: Som-Energia
- path: erppeek_wst
- path: somenergia-utils
  user: Som-Energia
- path: facturae
- path: sermepa # webforms
  user: Som-Energia
  tests:
  - ./setup.py test
# TODO: Pemissions required
#- path: webforms
#  user: Som-Energia
#  branch: API
#  tests:
#  - ./setup.py test
- path: plantmeter
  user: Som-Energia
  tests:
  - nosetests plantmeter
  - nosetests som_plantmeter/tests
- path: somenergia-generationkwh
  user: Som-Energia
  tests:
  - nosetests generationkwh
  - nosetests som_generationkwh/test
- path: sermepa # webforms
  user: Som-Energia
  tests:
  - ./setup.py test
- path: FACe_lib
- path: FACe_signer
- path: giscedata_facturacio_indexada_som
  user: Som-Energia
- path: somenergia-tomatic
  user: Som-Energia
  tests:
  - nosetests


editablePackages:

# Warning: in dependency order

# gisce
- aeroolib/aeroolib
- sepa
- libfacturacioatr
- switching
- libComXML
- sippers
- qreu
- enerdata
- arquia
- ooop
- empowering
- cchloader
- gestionatr
- sii
- ooquery
- erppeek_wst

# somenergia
- sermepa
- plantmeter
- somenergia-generationkwh
- facturae
- amoniak
- orakwlum_client
- CNMC-Client
- somenergia-utils



postgresUsers:
- somenergia
- sommonitor
- erp
- somarmota
- readonly




# vim: ts=2 et sw=2
